apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-mroz
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/psrivast1-tenant/my-app/devfile-sample-mroz@sha256:d6a4542f42b69124c0d540fd0a24c209f91571a0bde4ffa4205276394d058d58
        name: my-nodejs
        resources: {}
status: {}
